DROP TABLE IF EXISTS organization_admin CASCADE;
DROP TABLE IF EXISTS professional_organization CASCADE;
DROP TABLE IF EXISTS patient_professional CASCADE;
DROP TABLE IF EXISTS patient_details CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS app_review CASCADE;
DROP TYPE IF EXISTS evaluation CASCADE;
DROP TYPE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS app_device CASCADE;
DROP TABLE IF EXISTS device CASCADE;
DROP TABLE IF EXISTS app_platform CASCADE;
DROP TABLE IF EXISTS platform CASCADE;
DROP TABLE IF EXISTS app_recommendation CASCADE;
DROP TABLE IF EXISTS app_tag CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS app_links CASCADE;
DROP TABLE IF EXISTS app CASCADE;
DROP TABLE IF EXISTS organization_details CASCADE;
DROP TABLE IF EXISTS user_hierarchy CASCADE;
DROP TABLE IF EXISTS session_lookup CASCADE;
DROP TABLE IF EXISTS user_details CASCADE;

DROP SCHEMA IF EXISTS staging CASCADE;
DROP FUNCTION IF EXISTS trigger_app_view_loader() CASCADE;
DROP FUNCTION IF EXISTS trigger_user_details_loader() CASCADE;

DROP FUNCTION IF EXISTS trigger_app_recommendation_loader() CASCADE;
DROP FUNCTION IF EXISTS trigger_app_review_loader() CASCADE;
